---
title: "ccrcc_6x_preproc"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ccrcc_6x_preproc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(demuxSNPpaperfigures)
library(SingleCellExperiment)
library(scater)
library(Matrix)
library(demuxmix)
```


## Data loading


````{r}

path=c("/data/yufei/210827_10X_KW9275_bcl/cellranger-6.1.1/GRCh38/BRI-1348/outs/filtered_feature_bc_matrix")

matrix<-readMM(paste(path,"/matrix.mtx.gz",sep=""))
barcodes<-read.table(paste(path,"/barcodes.tsv.gz",sep=""))
features<-read.table(paste(path, "/features.tsv.gz",sep=""))

rownames(matrix)<-features$V2
colnames(matrix)<-barcodes$V1

rna<-matrix[features$V3=="Gene",]
hto<-matrix[grep("Hashtag",features$V1),]

se_hto<-SummarizedExperiment(assays = list(counts = hto))
sce<-SingleCellExperiment(list(counts=rna))
altExp(sce,"HTO")<-se_hto
mainExpName(sce)<-"RNA"
sce
````


````{r}

dmm<-demuxmix(hto=as.matrix(hto),rna=colSums(rna))
pAcpt(dmm) <- 0.95
classLabels <- dmmClassify(dmm)


table(classLabels$HTO)

````

````{r}
path=c("/data/scratch/nextflow/ccrcc_raw/")
set.seed(1)
for (i in seq_along(rownames(hto))) {
  hashtag<-rownames(hto)[i]
  barcodes<-colnames(rna)[classLabels$HTO==hashtag]
  #index<-sample(length(barcodes),50)
  print(length(barcodes))
  print(paste(path,hashtag,"_ccrcc_barcodes.tsv",sep=""))
  #print(head(index))
  write.table(barcodes,
              file=paste(path,hashtag,"_ccrcc_barcodes.tsv",sep=""),
              col.names = FALSE,
              row.names = FALSE,
              quote=FALSE)
}

````
