---
title: "Figure-2-hashing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure-2-hashing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(demuxSNPpaperfigures)
library(demuxSNP)
library(SingleCellExperiment)
library(Seurat)
library(demuxmix)
library(dittoSeq)
library(ggpubr)
library(gridExtra)
library(scater)
library(grid)
library(dplyr)

```

````{r}

source("../R/hto_sim.R")
source("../R/plot_hashtag.R")
````

# hashing based demultiplexing performance decreases with hashing quality:

## high qual 

````{r fig.width=12,fig.height=3}

mat<-logimat(6,nsinglet=rep(1000,6), ndoub = 1500, nneg=500)
size_sig=rep(10,6)
size_bg=rep(10,6)
mu_sig=rep(50,6)
mu_bg=rep(5,6)
counts<-draw_counts(size_sig = size_sig, size_bg = size_bg, mu_sig = mu_sig, mu_bg = mu_bg, mat = mat, seed = 1)

dim(counts)
truth<-colnames(counts)
df<-data.frame(t(counts))
plot<-plot_hashtag(df)
do.call(grid.arrange,c(plot,nrow=1))
````

## low qual

````{r fig.width=12,fig.height=3}

# mat<-logimat(6,nsinglet=c(100,200,1000,400,500,800), ndoub = 500, nneg=50)
# # size_sig=rep(10,6)
# # size_bg=rep(20,6)
# # mu_sig=rep(50,6)
# # mu_bg=rep(5,6)
# size_sig=rep(10,6)
# size_bg=rep(7,6)
# mu_sig=c(500,500,400,500,200,400)
# mu_bg=c(110,120,90,100,60,80)
# counts_low<-draw_counts(size_sig = size_sig, size_bg = size_bg, mu_sig = mu_sig, mu_bg = mu_bg, mat = mat, seed = 1)
# 
# dim(counts_low)
# truth_low<-colnames(counts_low)
# df<-data.frame(t(counts_low))
# plot<-plot_hashtag(df,ylim=c(0,2000))
# do.call(grid.arrange,c(plot,nrow=1))

load("/data/projects/demuxSNP/nextflow/ccrcc_out/demuxSNP_h/h_final_sce.rdata")
df_qual<-perCellQCMetrics(sce)
sce$qual<-df_qual$sum>1000 | df_qual$detected>750
table(sce$qual)
sce<-sce[,sce$qual==TRUE]
hto_j<-counts(altExp(sce,"HTO"))
dim(hto_j)
df_j<-data.frame(t(hto_j))

counts_low<-hto_j
library(stringr)
sce$truth<-str_replace(sce$truth,"K","Hashtag")
truth_low<-sce$truth

table(sce$truth)
````

````{r}
load("/data/projects/demuxSNP/nextflow/ccrcc_out/demuxSNP_h/h_final_sce.rdata")
train_cells<-sce$train
predict_cells<-!sce$train
k=10
d=200
   train <- counts(altExp(sce, "SNP"))[, train_cells == TRUE]
    train[train == -1] <- 0
    labels <- sce$labels[train_cells == TRUE]
    labels <- droplevels(labels)
    colnames(train) <- labels
    combs <- expand.grid(levels(labels), levels(labels))
    combs <- combs[combs$Var1 != combs$Var2, ]
    p <- combn(unique(combs$Var1), 2)
    combs_joined <- paste(p[1, ], p[2, ])
    all <- matrix(data = NA, nrow = dim(altExp(sce, "SNP"))[1], 
        ncol = d * length(combs_joined))
    for (i in seq_along(combs_joined)) {
        l1 <- as.character(combs$Var1[i])
        l2 <- as.character(combs$Var2[i])
        d1 <- train[, labels == l1]
        d2 <- train[, labels == l2]
        s1 <- sample(seq_len(dim(d1)[2]), d, replace = TRUE)
        s2 <- sample(seq_len(dim(d2)[2]), d, replace = TRUE)
        doubs <- d1[, s1] == 1 | d2[, s2] == 1
        doubs <- doubs * 1
        doubs[doubs == 0] <- c(0)
        all[, c(1 + (i - 1) * d):c(d + (i - 1) * d)] <- doubs
        colnames(all) <- rep("Doublet", dim(all)[2])
    }
    train_all <- cbind(train, all)
    pred <- as.data.frame(counts(altExp(sce, "SNP"))[, predict_cells == 
        TRUE])
    pred[pred == -1] <- 0
    y = as.integer(as.factor(colnames(train_all)))
    result_kern <- KernelKnn::KernelKnn(data = t(train_all), TEST_data = t(pred), 
        y = y, k = k, Levels = seq_along(levels(as.factor(colnames(train_all)))), regression = F, method = "jaccard_coefficient")
    ID <- apply(result_kern, 1, which.max)
    z <- levels(as.factor(colnames(train_all)))
    names(z)<-seq_along(z)
    ID<-recode(as.character(ID), !!!z)
#> [1] "Apple"  "Banana" "Banana" "Apple"

    sce$knn_jacc <- as.character(sce$labels)
    sce$knn_jacc[predict_cells == TRUE] <- as.character(as.factor(ID))
    sce$knn_jacc <- as.factor(sce$knn_jacc)
  table(sce$knn_jacc,sce$truth)
  
  adjustedRandIndex(sce$knn,sce$truth)
  adjustedRandIndex(sce$knn_jacc,sce$truth)
  
  snp<-altExp(sce,"SNP")
  logcounts(snp)<-counts(snp)
  snp<-scater::runPCA(snp)
  snp$class<-sce$truth
  snp$classdoub<-sce$truthalldoub
  snp$knn<-sce$knn_jacc
  snp<-runTSNE(snp)
  dittoDimPlot(snp,reduction.use="TSNE","class")
    dittoDimPlot(snp,reduction.use="TSNE","classdoub")
  dittoDimPlot(snp,reduction.use="TSNE","knn")
    dittoDimPlot(snp,reduction.use="PCA","knn")
    
    sce$truth<-gsub("K","Hashtag",sce$truth)
    
    sum(sce$knn==sce$truth)/length(sce$truth)
    sum(sce$knn_jacc==sce$truth)/length(sce$truth)
````

````{r eval=FALSE}
methods<-c("htodemux","bff_raw","bff_cluster","dropletutils","multiseq","gmm_demux")
library(cellhashR)
colnames(counts)<-seq_len(dim(counts)[2])
chr<-GenerateCellHashingCalls(counts,
                              methods=methods,
                              doTSNE = FALSE)

chr<-chr[order(as.numeric(chr$cellbarcode)),]
chr$gt<-truth

colnames(counts_low)<-seq_len(dim(counts_low)[2])
chr_low<-GenerateCellHashingCalls(counts_low,
                              methods=methods,
                              doTSNE = FALSE)

chr_low<-chr_low[order(as.numeric(chr_low$cellbarcode)),]
chr_low$gt<-truth_low

library(caret)
methods=c("htodemux","bff_cluster","bff_raw")
df_full<-data.frame()
for (i in seq_along(methods)) {
  m<-methods[i]
  data_ch=chr[[m]]
  ref_ch=chr[['gt']]
  data_fac<-factor(data_ch,union(data_ch,ref_ch))
  ref_fac<-factor(ref_ch,union(data_ch,ref_ch))
  cf<-confusionMatrix(data=data_fac,reference=ref_fac)
  recall<-cf$byClass[,5]
  precision<-cf$byClass[,6]
  df<-data.frame(class=rownames(cf$byClass),data='high',method=m,precision=precision,recall=recall)
  df_full<-rbind(df_full,df)
}



for (i in seq_along(methods)) {
  m<-methods[i]
  data_ch=chr_low[[m]]
  ref_ch=chr_low[['gt']]
  data_fac<-factor(data_ch,union(data_ch,ref_ch))
  ref_fac<-factor(ref_ch,union(data_ch,ref_ch))
  cf<-confusionMatrix(data=data_fac,reference=ref_fac)
  recall<-cf$byClass[,5]
  precision<-cf$byClass[,6]
  df<-data.frame(class=rownames(cf$byClass),data='low',method=m,precision=precision,recall=recall)
  df_full<-rbind(df_full,df)
}

df_full<-df_full[!is.na(df_full$precision),]
## barplot
ggbarplot(df_full,x='method',y='recall', add = c("mean_se", "jitter"),color="data",position=position_dodge())
ggbarplot(df_full,x='method',y='precision', add = c("mean_se", "jitter"),color="data",position=position_dodge())

ggboxplot(df_full,x='method',y='recall', add = c("mean_se", "jitter"),color="data", label='class',label.select = list(top.down = 1))
ggboxplot(df_full,x='method',y='precision', add = c("mean_se", "jitter"),color="data", label='class',label.select = list(top.down = 1))
````

````{r fig.height=3 , fig.width=12}

hto_low<-as.matrix(counts(altExp(sce,"HTO")))
plot<-plot_hashtag(data.frame(t(log(hto_low+1))),xlim=c(0,10),ylim=c(0,2000),breaks=get_breaks(n=6,from=0,to=10))
grid.arrange(grobs=plot,nrow=1,top=textGrob("Low quality hashing logcounts", gp=gpar(fontsize=20,font=8)))

hto_high<-as.matrix(counts(altExp(sce,"HTO_old")))
plot<-plot_hashtag(data.frame(t(log(hto_high+1))),xlim=c(0,10),ylim=c(0,2000),breaks=get_breaks(n=6,from=0,to=10))
grid.arrange(grobs=plot,nrow=1,top=textGrob("High quality hashing logcounts", gp=gpar(fontsize=20,font=8)))

````


````{r}
library(zellkonverter)
library(DropletUtils)
sce$truth<-gsub("K","Hashtag",sce$truth)
sce$truthalldoub<-gsub("K","Hashtag",sce$truthalldoub)
counts<-as.matrix(hto_high)
rna=counts(sce)[unique(rownames(sce)),]
colnames(rna)<-seq_len(dim(rna)[2])
write10xCounts("rna.h5",x=rna,type="HDF5",overwrite=TRUE)
h5File <- 'rna.h5'
DropletUtils::read10xCounts(h5File)
methods<-c("htodemux","bff_raw","bff_cluster","dropletutils","multiseq","gmm_demux","demuxmix")
library(cellhashR)
colnames(counts)<-seq_len(dim(counts)[2])
chr<-GenerateCellHashingCalls(counts,
                              methods=methods,
                              doTSNE = FALSE,
                              rawFeatureMatrixH5 = h5File)

chr<-chr[order(as.numeric(chr$cellbarcode)),]
chr$gt<-sce$truth

counts_low<-hto_low
colnames(counts_low)<-seq_len(dim(counts_low)[2])
chr_low<-GenerateCellHashingCalls(counts_low,
                              methods=methods,
                              doTSNE = FALSE,
                              rawFeatureMatrixH5 = h5File)

chr_low<-chr_low[order(as.numeric(chr_low$cellbarcode)),]
chr_low$gt<-sce$truth

library(caret)
methods=c("htodemux","bff_cluster","bff_raw","gmm_demux","demuxmix")
df_full<-data.frame()
for (i in seq_along(methods)) {
  m<-methods[i]
  data_ch=chr[[m]]
  ref_ch=chr[['gt']]
  data_fac<-factor(data_ch,union(data_ch,ref_ch))
  ref_fac<-factor(ref_ch,union(data_ch,ref_ch))
  cf<-confusionMatrix(data=data_fac,reference=ref_fac)
  recall<-cf$byClass[,6]
  precision<-cf$byClass[,5]
  df<-data.frame(class=rownames(cf$byClass),data='high',method=m,precision=precision,recall=recall)
  df_full<-rbind(df_full,df)
}


for (i in seq_along(methods)) {
  m<-methods[i]
  data_ch=chr_low[[m]]
  ref_ch=chr_low[['gt']]
  data_fac<-factor(data_ch,union(data_ch,ref_ch))
  ref_fac<-factor(ref_ch,union(data_ch,ref_ch))
  cf<-confusionMatrix(data=data_fac,reference=ref_fac)
  recall<-cf$byClass[,6]
  precision<-cf$byClass[,5]
  df<-data.frame(class=rownames(cf$byClass),data='low',method=m,precision=precision,recall=recall)
  df_full<-rbind(df_full,df)
}

df_full<-df_full[!is.na(df_full$recall),]
df_full$class<-gsub("Class: ","",df_full$class)
## barplot
ggbarplot(df_full,x='method',y='recall', add = c("mean_se", "jitter"),color="data",position=position_dodge())
ggbarplot(df_full,x='method',y='precision', add = c("mean_se", "jitter"),color="data",position=position_dodge())

````


````{r fig.height=5,fig.width=12}
rec<-ggboxplot(df_full,x='method',y='recall', add = c("mean_se", "jitter"),color="data",,repel=TRUE)
prec<-ggboxplot(df_full,x='method',y='precision', add = c("mean_se", "jitter"),color="data",,repel=TRUE)

ggpar(prec,legend.title = "data quality",ylim = c(0,1)) + ggpar(rec,legend.title="data quality",ylim = c(0,1))

````

````{r eval=FALSE}
set.seed(2)
z<-matrix(0,nrow=6,ncol=dim(broad.sce.sim)[2])
for (i in 1:6) {
  names<-c("K1","K2","K3","K4","K5","K6")
  n<-names[i]
  z[i,broad.sce.sim$truth==n]<-1
  
}

nsinglet=as.vector(table(broad.sce.sim$truth[broad.sce.sim$truth!="Doublet"]))[1:6]
ngroups=6
ndoub=sum(broad.sce.sim$truth=="Doublet")
doub<-matrix(0,nrow=ngroups,ncol=ndoub)
  prob=proportions(nsinglet)
  ind<-replicate(n=ndoub,sample(seq_len(ngroups),size=2,prob=prob))
  for (j in seq_len(ndoub)) {
    doub[ind[,j],j]<-1
  }
z[,broad.sce.sim$truth=="Doublet"]<-doub

size_sig=rep(10,6)
size_bg=rep(7,6)
mu_sig=c(500,500,400,500,200,400)
mu_bg=c(110,120,90,100,60,80)

counts<-draw_counts(size_sig = size_sig, size_bg = size_bg, mu_sig = mu_sig, mu_bg = mu_bg, mat = z)

````


````{r}
total_nneg<-c()
total_acc<-c()
total_nnegpc<-c()
chr_low$demuxsnp<-sce$knn
methods=c("htodemux","bff_cluster","bff_raw","gmm_demux","demuxmix","demuxsnp")
for (i in seq_along(methods)) {
  m<-methods[i]
  data_ch=chr_low[[m]]
  ref_ch=chr_low$gt
  nneg<-sum(data_ch=="Negative")
  acc<-sum(data_ch==ref_ch)/length(data_ch)
  print(nneg)
  print(acc)
  total_nneg[i]<-nneg
  total_nnegpc[i]<-nneg/length(ref_ch)
  total_acc[i]<-acc
}
names(total_nneg)<-methods
names(total_nnegpc)<-methods
names(total_acc)<-methods
df_methods_low<-data.frame(method=methods,pc_neg=total_nnegpc,accuracy=total_acc)
df_methods_low$data<-"low"

for (i in seq_along(methods)) {
  m<-methods[i]
  data_ch=chr[[m]]
  ref_ch=chr$gt
  nneg<-sum(data_ch=="Negative")
  acc<-sum(data_ch==ref_ch)/length(data_ch)
  print(nneg)
  print(acc)
  total_nneg[i]<-nneg
  total_nnegpc[i]<-nneg/length(ref_ch)
  total_acc[i]<-acc
}
names(total_nneg)<-methods
names(total_nnegpc)<-methods
names(total_acc)<-methods

df_methods_high<-data.frame(method=methods,pc_neg=total_nnegpc,accuracy=total_acc)
df_methods_high$data="high"
df_methods<-rbind(df_methods_high,df_methods_low)
ggbarplot(df_methods,x='method',y='accuracy',fill = 'data',position=position_dodge(),color = 'data',title='Overall Classificaton Accuracy between methods and high/low quality hashing',xlab='method',ylab='Overall CLassification Accuracy')+ylim(0,1)
ggbarplot(df_methods,x='method',y='pc_neg',fill = 'data',position=position_dodge(),color = 'data' ,title='% Negatives assigned between methods and high/low quality hashing',xlab='method',ylab='% hashing negatives')
````


````{r}
rna<-colSums(counts(sce))
dmm<-demuxmix(hto=counts_low,rna=rna)
#pAcpt(dmm) <- 0
dmmlabels<-dmmClassify(dmm)
dmmlabels$HTO[dmmlabels$Type=="negative"]<-"Negative"
dmmlabels$HTO[dmmlabels$Type=="multiplet"]<-"Doublet"
table(dmmlabels$HTO)
table(dmmlabels$HTO,sce$truth)
sum(dmmlabels$HTO==sce$truth)/length(dmmlabels$HTO)
sce$dmm<-dmmlabels$HTO

#demuxSNP
sce$knn<-as.character(sce$knn)
sce$knn<-factor(sce$knn,levels=c(unique(sce$knn),"Negative"))
sce$truth<-factor(sce$truth,levels=c(levels(sce$knn),"uncertain"))
cf<-confusionMatrix(data=sce$knn,reference=sce$truth)
cf$byClass[,5:6]
cf_demuxSNP<-as.data.frame(cf$byClass[,5:6])
cf_demuxSNP$algorithm<-"demuxSNP"
cf_demuxSNP$group<-gsub("Class: ","",rownames(cf_demuxSNP))

#demuxmix
sce$dmm<-factor(sce$dmm,levels=c(unique(sce$dmm)))
cf<-confusionMatrix(data=sce$dmm,reference=sce$truth)
cf$byClass[,5:6]
cf_demuxmix<-as.data.frame(cf$byClass[,5:6])
cf_demuxmix$algorithm<-"demuxmix"
cf_demuxmix$group<-gsub("Class: ","",rownames(cf_demuxmix))

compar<-rbind(cf_demuxSNP,cf_demuxmix)
compar<-compar[c(grep("Hashtag",compar$group), grep("Doublet",compar$group)),]
compar$group<-factor(compar$group,levels=c("Hashtag1","Hashtag2","Hashtag3","Hashtag4","Hashtag5","Hashtag6","Doublet"))
ggscatter(compar,x='Recall',y='Precision',color = 'algorithm',shape='group',label='group',palette = dittoColors(),size=4,legend="right",ellipse=TRUE,ellipse.type = "convex")+ xlim(0.2,1)+ylim(0.2,1)
ggscatter(compar,x='Recall',y='Precision',color = 'group',shape='algorithm',label='group',palette = dittoColors(),size=4,legend="right")+ xlim(0,1)+ylim(0,1)

````

````{r}

sum(as.character(sce$knn)==as.character(sce$truth))/length(sce$truth)
sum(as.character(sce$dmm)==as.character(sce$truth))/length(sce$truth)

sce$knn<-as.character(sce$knn)
sce$dmm<-as.character(sce$dmm)
````


````{r fig.height=6,fig.width=4}
dmm<-c()
knn<-c()
for (i in 1:7) {
  h<-levels(sce$truth)[i]
  dmm[i]<-sum((sce$dmm[sce$truth==h]==sce$truth[sce$truth==h])/length(sce$truth[sce$truth==h]))
  knn[i]<-sum((sce$knn[sce$truth==h]==sce$truth[sce$truth==h])/length(sce$truth[sce$truth==h]))
}

df<-data.frame(demuxmix=dmm,demuxSNP=knn)
rownames(df)<-levels(sce$truth)[1:7]
df$label<-levels(sce$truth)[1:7]


ggpaired(df, cond1 = "demuxmix", cond2 = "demuxSNP",
    color="label", palette = "jco",ylab="per-label accuracy")
````

````{r}



````

## Misassigned cells generally fall between signal and background peak:

````{r}


````



## Combined hashing and SNPs approachs performs better than standalone hashing algorithms.

````{r}



````

````{r eval=FALSE}

#demuxmix

broad.sce.sim$dmm<-as.factor(gsub("Hashtag","K",dmmlabels$HTO))
cf<-confusionMatrix(data=broad.sce.sim$dmm,reference=broad.sce.sim$truth)
cf$byClass[,5:6]
cf_demuxmix<-as.data.frame(cf$byClass[,5:6])
cf_demuxmix$algorithm<-"demuxmix"
cf_demuxmix$group<-gsub("Class: ","",rownames(cf_demuxmix))

````

````{r eval=FALSE}

compar<-rbind(cf_demuxSNP,cf_demuxmix)
compar<-compar[c(grep("K",compar$group), grep("Doublet",compar$group)),]
compar$group<-factor(compar$group,levels=c("K1","K2","K3","K4","K5","K6","Doublet"))
ggscatter(compar,x='Recall',y='Precision',color = 'group',shape='algorithm',label='group',palette = dittoColors(),size=4,legend="right")+ xlim(0.2,1)+ylim(0.2,1)

````



