---
title: "collect_soup_results"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pbmc_4x_preproc}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(demuxSNPpaperfigures)
library(SingleCellExperiment)
library(scater)
library(Matrix)
library(demuxmix)
library(demuxSNP)
library(dittoSeq)
````



````{r}

n=c(10,10,10,10)
ds=c(2500,500,250,125)
key=c("a","b","c","d")

doub10ari<-collect(ndoub=n,ds=ds,key=key)
doub20ari<-collect(ndoub=rep(20,4),ds=ds,key=c("e","f","g","h"))
doub30ari<-collect(ndoub=rep(30,4),ds=ds,key=c("i","j","k","l"))
doub40ari<-collect(ndoub=rep(40,4),ds=ds,key=c("m","n","o","p"))
doub50ari<-collect(ndoub=rep(50,4),ds=ds,key=c("q","r","s","t"))

plot(ds,doub10ari,xlab="smallest group size")
plot(ds,doub40ari,xlab="smallest group size")
````

````{r fig.width=5,fig.height=6}

plot(n,ari_n,xlab="% doublets")

````

````{r}

collect<-function(ndoub,ds,key) {
  library(readr)
  library(dplyr)
  library(caret)
  library(mclust)
  n<-ndoub
  ari_n<-c(); recall_n<-c();precision_n<-c()
  
  for (i in seq_along(key)) {
  ## ground truth
  lookup<-read_tsv(paste("/data/scratch/nextflow/ccrcc_out/lookup_table_doublets_pbmc_",key[i],"_", n[i],"pc.tsv",sep=""),show_col_types = FALSE)
  doublet_barcodes<-read_tsv(paste("/data/scratch/nextflow/ccrcc_out/barcodes_merged_pbmc_",key[i],"_", n[i], "pc.tsv",sep=""),col_names = "barcode",show_col_types = FALSE)
  label<-substr(doublet_barcodes$barcode,start=18,stop=19)
  label[doublet_barcodes$barcode %in% lookup$replacement]<-"Doublet"
  
  ## souporcell results
  souporcell<-read.table(file=paste("/data/scratch/nextflow/ccrcc_out/pbmc_",key[i],"_",n[i],"/clusters.tsv",sep=""), sep='\t',header=TRUE)
  souporcell$assignment[souporcell$status=="doublet"]<-"Doublet"
  souporcell$assignment[souporcell$status=="unassigned"]<-"unassigned"

  ## recode souporcell labels (need to add if else to handle souporcell missing a cluster)
  t<-table(label,souporcell$assignment)
  k<-t[grep("[0-9]",rownames(t)),grep("[0-9]",colnames(t))]
  kp<-proportions(k+1,1)

  m<-max.col(kp)
  vals<-kp[cbind(seq_along(m),m)]
  m[which.min(vals)]<-c(setdiff(seq_along(m),m[-c(which.min(vals))]))

  y<-rownames(kp)
  z<-colnames(kp)[m]
  w<-as.character(z)
  names(w)<-as.character(y)
  soup_new<-recode(souporcell$assignment,!!!setNames(y,z))

  print(table(label))
  print(table(soup_new))
  print(table(label,soup_new))
 
    ## evaluate performance
  data=factor(soup_new, levels=sort(union(soup_new,label)))
  ref=factor(label, levels=sort(union(soup_new,label)))
  ari<-adjustedRandIndex(data,ref)
  cf<-confusionMatrix(data=data,reference=ref)
  prec<-cf$byClass[3,5]
  rec<-cf$byClass[3,6]
  print(ari)
  ari_n[i]<-ari
  recall_n[i]<-rec
  precision_n[i]<-prec
  print(key[i])
  res<-list("ari"=ari_n,"recall"=recall_n,"precision"=precision_n)
}
return(res)
}

````



````{r fig.width=4,fig.height=4}

n=c(5,10,15,20,25,30,35,40,45,50)
ds=c(2500,500,250,125)
key=c("a","b","c","d","e","f","g","h","i","j")

ccrcc_ari<-collect(ndoub=n,ds=ds,key=key)

plot(n,ccrcc_ari$precision,xlab="doublet rate")
library(ggpubr)
df_p=data.frame(key=key,doublets=n,metric=ccrcc_ari$precision,type="precision")
df_r=data.frame(key=key,doublets=n,metric=ccrcc_ari$recall,type="recall")
df<-rbind(df_p,df_r)
ggline(data=df, x="doublets", y="metric", linetype="type", xlab = "% doublets")
````

