---
title: "Figure-3-snps"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure-3-snps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}

library(demuxSNPpaperfigures)
library(dittoSeq)
library(ggpubr)
library(ggalluvial)
library(data.table)
```

## Functions

````{r}


collect_soup <- function(ndoub, key, seed) {
  library(readr)
  library(dplyr)
  library(caret)
  library(mclust)
  n <- ndoub
  df_full <- data.frame()
  
  for (i in seq_along(key)) {
    ## ground truth
    lookup <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/lookup_table_doublets_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        show_col_types = FALSE
      )
    doublet_barcodes <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/barcodes_merged_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        col_names = "barcode",
        show_col_types = FALSE
      )
    label <- substr(doublet_barcodes$barcode,
                    start = 18,
                    stop = 19)
    #label[doublet_barcodes$barcode %in% lookup$replacement]<-"Doublet"
    label[doublet_barcodes$barcode %in% lookup$replacement[substr(lookup$original, 18, 19) !=
                                                             substr(lookup$replacement, 18, 19)]] <-
      "Doublet"
    
    ## souporcell results, looping through different seeds
    for (j in seq_along(seed)) {
      s <- seed[j]
      souporcell <-
        read.table(
          file = paste(
            "/data/projects/demuxSNP/nextflow/ccrcc_out/soup_",
            key[i],
            "_",
            n[i],
            "_",
            s,
            "/clusters.tsv",
            sep = ""
          ),
          sep = '\t',
          header = TRUE
        )
      souporcell$assignment[souporcell$status == "doublet"] <-
        "Doublet"
      souporcell$assignment[souporcell$status == "unassigned"] <-
        "unassigned"
      
      ## recode souporcell labels
      t <- table(label, souporcell$assignment)
      k <- t[grep("[0-9]", rownames(t)), grep("[0-9]", colnames(t))]
      kp <- proportions(k + 1, 1)
      
      m <- max.col(kp)
      vals <- kp[cbind(seq_along(m), m)]
      m[which.min(vals)] <-
        c(setdiff(seq_along(m), m[-c(which.min(vals))]))
      
      y <- rownames(kp)
      z <- colnames(kp)[m]
      w <- as.character(z)
      names(w) <- as.character(y)
      soup_new <- recode(souporcell$assignment,!!!setNames(y, z))
      
      print(table(label))
      print(table(soup_new))
      print(table(label, soup_new))
      
      ## evaluate performance
      data = factor(soup_new, levels = sort(union(soup_new, label)))
      ref = factor(label, levels = sort(union(soup_new, label)))
      ari <- adjustedRandIndex(data, ref)
      acc <- accuracy_vec(data, ref)
      cf <- confusionMatrix(data = data, reference = ref)
      prec <- cf$byClass[3, 5]
      rec <- cf$byClass[3, 6]
      doublet_prec<-cf$byClass["Class: Doublet","Precision"]
      doublet_rec<-cf$byClass["Class: Doublet", "Recall"]
      doublet_acc<-proportions(table(data))["Doublet"]
      doublet_meas<-proportions(table(ref))["Doublet"]
      df <- data.frame(
        key = key[i],
        doublets = n[i],
        accuracy = acc,
        ari = ari,
        precision = prec,
        recall = rec,
        doublet_precison=doublet_prec,
        doublet_rec= doublet_rec,
        doublet_acc=doublet_acc,
        doublet_meas=doublet_meas,
        seed = s
      )
      df_full <- rbind(df_full, df)
    }
  }
  return(df_full)
}

collect_vireo <- function(ndoub, key, seed) {
  library(readr)
  library(dplyr)
  library(caret)
  library(mclust)
  n <- ndoub
  #ari_n<-c(); recall_n<-c();precision_n<-c()
  df_full <- data.frame()
  for (i in seq_along(key)) {
    ## ground truth
    lookup <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/lookup_table_doublets_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        show_col_types = FALSE
      )
    doublet_barcodes <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/barcodes_merged_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        col_names = "barcode",
        show_col_types = FALSE
      )
    label <- substr(doublet_barcodes$barcode,
                    start = 18,
                    stop = 19)
    #label[doublet_barcodes$barcode %in% lookup$replacement]<-"Doublet"
    label[doublet_barcodes$barcode %in% lookup$replacement[substr(lookup$original, 18, 19) !=
                                                             substr(lookup$replacement, 18, 19)]] <- "Doublet"
    
    ## souporcell results
    for (j in seq_along(seed)) {
      s<-seed[j]
      vireo <-
        read.table(
          file = paste(
            "/data/projects/demuxSNP/nextflow/ccrcc_out/vireo_",
            key[i],
            "_",
            n[i],
            "_",
            s,
            "/donor_ids.tsv",
            sep = ""
          ),
          sep = '\t',
          header = TRUE
        )
      vireo <- vireo[match(doublet_barcodes$barcode, vireo$cell), ]
      vireo$donor_id[vireo$donor_id == "doublet"] <- "Doublet"
      #souporcell$assignment[souporcell$status=="unassigned"]<-"unassigned"
      
      ## recode souporcell labels (need to add if else to handle souporcell missing a cluster)
      t <- table(label, vireo$donor_id)
      k <- t[grep("[0-9]", rownames(t)), grep("[0-9]", colnames(t))]
      kp <- proportions(k + 1, 1)
      
      m <- max.col(kp)
      vals <- kp[cbind(seq_along(m), m)]
      m[which.min(vals)] <-
        c(setdiff(seq_along(m), m[-c(which.min(vals))]))
      
      y <- rownames(kp)
      z <- colnames(kp)[m]
      w <- as.character(z)
      names(w) <- as.character(y)
      vireo_new <- recode(vireo$donor_id, !!!setNames(y, z))
      
      print(table(label))
      print(table(vireo_new))
      print(table(label, vireo_new))
      
      ## evaluate performance
      data = factor(vireo_new, levels = sort(union(vireo_new, label)))
      ref = factor(label, levels = sort(union(vireo_new, label)))
      ari <- adjustedRandIndex(data, ref)
      acc <- accuracy_vec(data, ref)
      cf <- confusionMatrix(data = data, reference = ref)
      prec <- cf$byClass[3, 5]
      rec <- cf$byClass[3, 6]
      # print(ari)
      # ari_n[i]<-ari
      # recall_n[i]<-rec
      # precision_n[i]<-prec
      # print(key[i])
      # res<-list("ari"=ari_n,"recall"=recall_n,"precision"=precision_n)
      df <- data.frame(
        key = key[i],
        doublets = n[i],
        accuracy = acc,
        ari = ari,
        precision = prec,
        recall = rec,
        seed = s
      )
      df_full <- rbind(df_full, df)
    }
  }
  return(df_full)
}

collect_demuxsnp <- function(ndoub, key, seed) {
  library(readr)
  library(dplyr)
  library(caret)
  library(mclust)
  n <- ndoub
  #ari_n<-c(); recall_n<-c();precision_n<-c();acc_n<-c()
  df_full <- data.frame()
  
  for (i in seq_along(key)) {
    ## ground truth
    lookup <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/lookup_table_doublets_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        show_col_types = FALSE
      )
    doublet_barcodes <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/barcodes_merged_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        col_names = "barcode",
        show_col_types = FALSE
      )
    label <- substr(doublet_barcodes$barcode,
                    start = 18,
                    stop = 19)
    label[doublet_barcodes$barcode %in% lookup$replacement[substr(lookup$original, 18, 19) !=
                                                             substr(lookup$replacement, 18, 19)]] <- "Doublet"
    
    ## demuxSNP results
    for (j in seq_along(seed)) {
      s <- seed[j]
      demuxsnp <-
        read.table(
          file = paste(
            "/data/projects/demuxSNP/nextflow/ccrcc_out/demuxSNP_",
            key[i],
            "_",
            n[i],
            "_",
            s,
            "/",
            key[i],
            "_demuxSNP.tsv",
            sep = ""
          ),
          sep = ' ',
          header = TRUE
        )
      
      ds_reorder <-
        demuxsnp$demuxSNP_centroid_nottrain[match(
          substr(
            doublet_barcodes$barcode,
            start = 1,
            stop = 16
          ),
          substr(demuxsnp$barcode, start = 1, stop = 16)
        )]
      ds_recode <- gsub("Hashtag", "K", ds_reorder)
      #print(table(label))
      print(table(label,ds_reorder))
      ## evaluate performance
      data = factor(ds_recode, levels = sort(union(ds_recode, label)))
      ref = factor(label, levels = sort(union(ds_recode, label)))
      ari <- adjustedRandIndex(data, ref)
      acc <- accuracy_vec(data, ref)
      cf <- confusionMatrix(data = data, reference = ref)
      prec <- cf$byClass[3, 5]
      rec <- cf$byClass[3, 6]
      doublet_prec<-cf$byClass["Class: Doublet","Precision"]
      doublet_rec<-cf$byClass["Class: Doublet", "Recall"]
      doublet_acc<-proportions(table(data))["Doublet"]
      doublet_meas<-proportions(table(ref))["Doublet"]
      df <- data.frame(
        key = key[i],
        doublets = n[i],
        accuracy = acc,
        ari = ari,
        precision = prec,
        recall = rec,
        doublet_precison=doublet_prec,
        doublet_rec= doublet_rec,
        doublet_acc=doublet_acc,
        doublet_meas=doublet_meas,
        seed = s
      )
      df_full <- rbind(df_full, df)
    }
  }
  return(df_full)
}

collect_htoreader <- function(ndoub, key, seed) {
  library(readr)
  library(dplyr)
  library(caret)
  library(mclust)
  n <- ndoub
  #ari_n<-c(); recall_n<-c();precision_n<-c();acc_n<-c()
  df_full <- data.frame()
  
  for (i in seq_along(key)) {
    ## ground truth
    lookup <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/lookup_table_doublets_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        show_col_types = FALSE
      )
    doublet_barcodes <-
      read_tsv(
        paste(
          "/data/projects/demuxSNP/nextflow/ccrcc_out/barcodes_merged_pbmc_",
          key[i],
          "_",
          n[i],
          "pc.tsv",
          sep = ""
        ),
        col_names = "barcode",
        show_col_types = FALSE
      )
    label <- substr(doublet_barcodes$barcode,
                    start = 18,
                    stop = 19)
    label[doublet_barcodes$barcode %in% lookup$replacement[substr(lookup$original, 18, 19) !=
                                                             substr(lookup$replacement, 18, 19)]] <- "Doublet"
    
    ## demuxSNP results
    for (j in seq_along(seed)) {
      s <- seed[j]
      demuxsnp <-
        read.table(
          file = paste(
            "/data/projects/demuxSNP/nextflow/ccrcc_out/demuxSNP_",
            key[i],
            "_",
            n[i],
            "_",
            s,
            "/",
            key[i],
            "_demuxSNP.tsv",
            sep = ""
          ),
          sep = ' ',
          header = TRUE
        )
      demuxsnp$htoreadermulti[demuxsnp$htoreadermulti=="doublet"]<-"Doublet"
      t <- table(label, demuxsnp$htoreadermulti)
      
      ds_reorder <-
        demuxsnp$htoreadermulti[match(
          substr(
            doublet_barcodes$barcode,
            start = 1,
            stop = 16
          ),
          substr(demuxsnp$barcode, start = 1, stop = 16)
        )]
      ds_recode <- gsub("Hashtag", "K", ds_reorder)
      print(table(label))
      
      ## evaluate performance
      data = factor(ds_recode, levels = sort(union(ds_recode, label)))
      ref = factor(label, levels = sort(union(ds_recode, label)))
      ari <- adjustedRandIndex(data, ref)
      acc <- accuracy_vec(data, ref)
      cf <- confusionMatrix(data = data, reference = ref)
      prec <- cf$byClass[3, 5]
      rec <- cf$byClass[3, 6]
      doublet_prec<-cf$byClass["Class: Doublet","Precision"]
      doublet_rec<-cf$byClass["Class: Doublet", "Recall"]
      doublet_acc<-proportions(table(data))["Doublet"]
      doublet_meas<-proportions(table(ref))["Doublet"]
      df <- data.frame(
        key = key[i],
        doublets = n[i],
        accuracy = acc,
        ari = ari,
        precision = prec,
        recall = rec,
        doublet_precison=doublet_prec,
        doublet_rec= doublet_rec,
        doublet_acc=doublet_acc,
        doublet_meas=doublet_meas,
        seed = s
      )
      df_full <- rbind(df_full, df)
    }
  }
  return(df_full)
}

````



````{r}
library(yardstick)
n = c(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
key = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")
ccrcc_soup <- collect_soup(ndoub = n,
                           key = key,
                           seed = 1)
# ccrcc_vireo <- collect_vireo(ndoub = n,
#                            key = key,
#                            seed = 1:5)
ccrcc_demuxsnp <- collect_demuxsnp(ndoub = n,
                           key = key,
                           seed = 1:5)
ccrcc_htoreader <- collect_htoreader(ndoub=n,
                                     key=key,
                                     seed=1:5)
ccrcc_soup$method<-"souporcell"
#ccrcc_vireo$method<-"vireo"
ccrcc_demuxsnp$method<-"demuxSNP"
ccrcc_htoreader$method<-"HTOreader_multi"
ccrcc_all<-rbind(ccrcc_soup,ccrcc_demuxsnp,ccrcc_htoreader)
````

````{r fig.height=3.5,fig.width=9}
pal<-c('blue','red','black')
head(ccrcc_all)
g1<-ggline(data=ccrcc_all, x="doublets", y="accuracy", linetype="method", xlab = "% doublets",color="method",palette = pal,add = "mean_sd",title="Accuracy",size=0.5)
g2<-ggline(data=ccrcc_all, x="doublets", y="ari", linetype="method", xlab = "% doublets",color="method", palette=pal,add = "mean_sd",title="Adjusted Rand Index")

ggarrange(ggpar(g1,ylim = c(0,1)),ggpar(g2,ylim=c(0,1)),common.legend = TRUE)


````


````{r fig.height=3.5,fig.width=9}

head(ccrcc_all)
g1<-ggline(data=ccrcc_all, x="doublets", y="precision", linetype="method", xlab = "% doublets",color="method", palette=pal,add = "mean_se",title="K2 Precision")
g2<-ggline(data=ccrcc_all, x="doublets", y="recall", linetype="method", xlab = "% doublets",color="method", palette=pal,add = "mean_se",title="K2 Recall")

ggarrange(ggpar(g1,ylim = c(0,1)),ggpar(g2,ylim=c(0,1)),common.legend = TRUE,ncol=2)
````

````{r fig.width=9,fig.height=3.5}

head(ccrcc_all)
g1<-ggline(data=ccrcc_all, x="doublets", y="doublet_rec", linetype="method", xlab = "% doublets",color="method", palette=pal,add = "mean_sd",title="doublet recall",size=0.5)
g2<-ggline(data=ccrcc_all, x="doublets", y="doublet_precison", linetype="method", xlab = "% doublets",color="method", palette=pal,add = "mean_sd",title="doublet precision",size=0.5)

ggarrange(ggpar(g2,ylim = c(0,1)),ggpar(g1,ylim=c(0,1)),common.legend = TRUE)

````

````{r fig.height=3.5,fig.width=8}

h2_pr<-ggarrange(ggpar(g1,ylim = c(0,1)),ggpar(g2,ylim=c(0,1)),common.legend = TRUE,ncol=2)
h2_pr
ggsave(h2_pr,filename="../figures/hashtag2_pr.svg",device="svg",height=3,width=7)
getwd()
````



````{r}
key="i"
n=45
s=1
#load ground truth
  lookup<-read_tsv(paste("/data/projects/demuxSNP/nextflow/ccrcc_out/lookup_table_doublets_pbmc_",key,"_", n,"pc.tsv",sep=""),show_col_types = FALSE)
  doublet_barcodes<-read_tsv(paste("/data/projects/demuxSNP/nextflow/ccrcc_out/barcodes_merged_pbmc_",key,"_", n, "pc.tsv",sep=""),col_names = "barcode",show_col_types = FALSE)
  label<-substr(doublet_barcodes$barcode,start=18,stop=19)
  msms<-substr(lookup$original,18,19)!=substr(lookup$replacement,18,19)
  label[doublet_barcodes$barcode %in% lookup$replacement[msms]]<-"Doublet"
  
# load demuxsnp from key
#demuxsnp<-read.table(file=paste("/data/projects/demuxSNP/nextflow/ccrcc_out/demuxSNP_",key,"/",key,"_demuxSNP.tsv",sep=""), sep=' ',header=TRUE)
      demuxsnp <-
        read.table(
          file = paste(
            "/data/projects/demuxSNP/nextflow/ccrcc_out/demuxSNP_",
            key,
            "_",
            n,
            "_",
            s,
            "/",
            key,
            "_demuxSNP.tsv",
            sep = ""
          ),
          sep = ' ',
          header = TRUE
        )
  demuxsnp$demuxSNP[demuxsnp$demuxSNP=="negative"]<-"Doublet" ##remove when rerun
  demuxsnp$demuxSNP_jacc[demuxsnp$demuxSNP_jacc=="negative"]<-"Doublet" ##remove when rerun
ds_reorder<-demuxsnp$demuxSNP[match(substr(doublet_barcodes$barcode,start=1,stop=16),substr(demuxsnp$barcode,start=1,stop=16))]
ds_recode<-gsub("Hashtag","K",ds_reorder)

#load souporcell from key

souporcell<-read.table(file=paste("/data/projects/demuxSNP/nextflow/ccrcc_out/soup_",key,"_",n,"_1/clusters.tsv",sep=""), sep='\t',header=TRUE)
souporcell$assignment[souporcell$status=="doublet"]<-"Doublet"
souporcell$assignment[souporcell$status=="unassigned"]<-"unassigned"

  ## recode souporcell labels (need to add if else to handle souporcell missing a cluster)
  t<-table(label,souporcell$assignment)
  k<-t[grep("[0-9]",rownames(t)),grep("[0-9]",colnames(t))]
  kp<-proportions(k+1,1)

  m<-max.col(kp)
  vals<-kp[cbind(seq_along(m),m)]
  m[which.min(vals)]<-c(setdiff(seq_along(m),m[-c(which.min(vals))]))

  y<-rownames(kp)
  z<-colnames(kp)[m]
  w<-as.character(z)
  names(w)<-as.character(y)
  soup_new<-recode(souporcell$assignment,!!!setNames(y,z))

labels2<-factor(label,levels=unique(c(label,ds_recode,soup_new)))

#demuxSNP
ds_factor<-factor(ds_recode,levels=union(label,ds_recode))
cf<-confusionMatrix(data=ds_factor,reference=labels2)
cf$byClass[,5:6]
cf_demuxSNP<-as.data.frame(cf$byClass[,5:6])
cf_demuxSNP$algorithm<-"demuxSNP"
cf_demuxSNP$group<-gsub("Class: ","",rownames(cf_demuxSNP))

#souporcell
soup_factor<-factor(soup_new,levels=union(label,soup_new))
cf<-confusionMatrix(data=soup_factor,reference=labels2)
cf$byClass[,5:6]
cf_soup<-as.data.frame(cf$byClass[,5:6])
cf_soup$algorithm<-"souporcell"
cf_soup$group<-gsub("Class: ","",rownames(cf_soup))

compar<-rbind(cf_demuxSNP,cf_soup)
compar<-compar[c(grep("K",compar$group), grep("Doublet",compar$group)),]
compar$group<-factor(compar$group,levels=c("K1","K2","K3","K4","K5","K6","Doublet"))


````



````{r fig.height=5,fig.width=4}
s1<-soup_factor
s2<-soup_factor==labels2
t<-reshape2::melt(table(s1,s2))
df<-data.frame(group=t$s1,correct=t$s2,count=t$value)
df$group<-factor(df$group,levels=c("K1","K2","K3","K4","K5","K6","Doublet"))
df<-df[!is.na(df$group),]
ggbarplot(df,x='group',y='count',fill = "correct" ,legend="right",orientation = "horiz",palette = c("white","black")) +ylab("# cells")

````



````{r fig.height=7,fig.width=6}


df<-data.frame(soup=soup_factor,truth=labels2)
df<-as.data.frame(table(soup_factor,labels2))
df$assignment<-c(df$soup_factor==df$labels2)
df$assignment<-as.character(df$assignment)
df$Assignment<-recode(df$assignment,"TRUE"="correct","FALSE"="incorrect")
alluvial<-ggplot(data = df,
       aes(axis1 = labels2, axis2 = soup_factor, y = Freq)) +
  geom_alluvium(aes(fill = Assignment)) +
scale_fill_manual(values = c('correct' = "grey50", 'incorrect' = "red")) +
#  guides(fill = "none") +
  geom_stratum()+
  geom_text(stat = "stratum",
            aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Ground truth", "Souporcell assignment"),
                   expand = c(0.15, 0.05))

alluvial
````


````{r fig.height=7,fig.width=6}


df<-data.frame(demuxsnp=demuxsnp,truth=labels2)
df<-as.data.frame(table(ds_factor,labels2))
df$assignment<-c(as.character(df$ds_factor)==as.character(df$labels2))
df$assignment<-as.character(df$assignment)
df$Assignment<-recode(df$assignment,"TRUE"="correct","FALSE"="incorrect")
alluvial<-ggplot(data = df,
       aes(axis1 = labels2, axis2 = ds_factor, y = Freq)) +
  geom_alluvium(aes(fill = Assignment)) +
scale_fill_manual(values = c('correct' = "grey30", 'incorrect' = "red")) +
#  guides(fill = "none") +
  geom_stratum()+
  geom_text(stat = "stratum",
            aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("Ground truth", "demuxSNP assignment"),
                   expand = c(0.15, 0.05))

alluvial
````


````{r eval=TRUE, fig.width=3,fig.height=5}

list_of_files <- list.files(path = "/data/projects/demuxSNP/nextflow/ccrcc_out", recursive = TRUE,
                            pattern = "runtime.txt", 
                            full.names = TRUE)
#1) Use fread() w/ rbindlist() from the data.table package

#install.packages("data.table", repos = "https://cran.rstudio.com")


# Read all the files and create a FileName column to store filenames
DT <- rbindlist(sapply(list_of_files, fread, simplify = FALSE),
                use.names = TRUE, idcol = "FileName")

DT$method<-"souporcell"
DT$method[grep("demuxSNP_",DT$FileName)]<-"demuxSNP"
#DT$method[grep("vireo_",DT$FileName)]<-"vireo"
DT$time<-DT$V1/60/60
#DT<-DT[DT$method!="vireo",]
ggpar(ggbarplot(DT,x="method",y="time", add = c("mean_se", "jitter"),color="method",position=position_dodge()),ylim=c(0,max(DT$time)),ylab=c("time (h)"))
````

## Doublets

````{r}
doub_gt<-dplyr::distinct(ccrcc_all,doublets,doublet_meas)
doub_gt$method="Ground Truth"
doub_gt$doublet_acc<-doub_gt$doublet_meas
doub_gt$doublet_meas<-NULL
df_doub_method<-rbind(
  ccrcc_all[,c("doublets","doublet_acc","method")],
  doub_gt
)
df_doub_method$doublet_acc_pc<-df_doub_method$doublet_acc*100
gg<-ggline(df_doub_method,x="doublets",y=c("doublet_acc_pc"), linetype="method",color="method",palette=c('blue','grey','red','black'),add = "mean_sd",title="doublet precision",size=0.5,merge=TRUE,ylab = '% multisample doublets',xlab='% all doublets')
ggpar(gg,ylim=c(0,40))
````


}
````{r}

ncells=seq(5000,50000,5000)
ncells
pc_doubs=ncells/1000
n_doubs=pc_doubs*ncells/100
plot(ncells,n_doubs)

multi_2<-1/2*n_doubs
multi_4<-3/4*n_doubs
multi_6<-5/6*n_doubs



df_doubs<-data.frame(ncells=ncells,n_doubs=n_doubs,multi_2=multi_2,multi_4=multi_4,multi_6=multi_6)
head(df_doubs)
ggline(df_doubs,x="ncells",y=c("n_doubs","multi_2","multi_4","multi_6"),merge = TRUE)
````

````{r}
1/1:6
df_multi<-data.frame(prop=c(1/1:6,1-c(1/1:6)),type=c(rep('SSM',6),rep('MSM',6)),multiplexedsamples=c(1:6,1:6))

ggbarplot(df_multi,x='multiplexedsamples',y='prop',fill = 'type') + coord_flip()

````

